# 기본환경 설정

In [3]:
import os
try:
    from google.colab import userdata
    HF_KEY = userdata.get("HF_KEY")
except:
    from dotenv import load_dotenv
    load_dotenv()
    HF_KEY = os.getenv("HF_KEY")

In [4]:
import huggingface_hub
huggingface_hub.login(HF_KEY)

# 데이터 준비

In [5]:
import os
import sentencepiece as spm
from datasets import load_dataset

In [6]:
os.makedirs("spm_models", exist_ok=True)

## 영어

In [7]:
dataset_eng = load_dataset("fancyzhx/ag_news", split="train[:100]")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


README.md:   0%|          | 0.00/8.07k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/18.6M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/120000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/7600 [00:00<?, ? examples/s]

In [8]:
sentences_eng = dataset_eng["text"]
sentences_eng[:2]

["Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green again.",
 'Carlyle Looks Toward Commercial Aerospace (Reuters) Reuters - Private investment firm Carlyle Group,\\which has a reputation for making well-timed and occasionally\\controversial plays in the defense industry, has quietly placed\\its bets on another part of the market.']

In [9]:
with open("corpus_eng.txt", "w", encoding="utf-8") as f:
    for line in sentences_eng:
        f.write(line + "\n")

## 한국어

In [10]:
dataset_kor = load_dataset("daekeun-ml/naver-news-summarization-ko", split="train[:100]")

README.md:   0%|          | 0.00/787 [00:00<?, ?B/s]

train.csv:   0%|          | 0.00/66.3M [00:00<?, ?B/s]

validation.csv:   0%|          | 0.00/7.45M [00:00<?, ?B/s]

test.csv:   0%|          | 0.00/8.17M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/22194 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2466 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2740 [00:00<?, ? examples/s]

In [11]:
sentences_kor = dataset_kor["document"]
sentences_kor[:2]

['앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 했습니다. 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했습니다. 류환홍 기자가 보도합니다. 기자 수출은 최고의 실적을 보였지만 수입액이 급증하면서 올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록했습니다. 정부가 수출확대에 총력을 기울이기로 한 것은 원자재 가격 상승 등 대외 리스크가 가중되는 상황에서 수출 증가세 지속이야말로 한국경제의 회복을 위한 열쇠라고 본 것입니다. 추경호 경제부총리 겸 기획재정부 장관 정부는 우리 경제의 성장엔진인 수출이 높은 증가세를 지속할 수 있도록 총력을 다하겠습니다. 우선 물류 부담 증가 원자재 가격 상승 등 가중되고 있는 대외 리스크에 대해 적극 대응하겠습니다. 특히 중소기업과 중견기업 수출 지원을 위해 무역금융 규모를 연초 목표보다 40조 원 늘린 301조 원까지 확대하고 물류비 부담을 줄이기 위한 대책도 마련했습니다. 이창양 산업통상자원부 장관 국제 해상운임이 안정될 때까지 월 4척 이상의 임시선박을 지속 투입하는 한편 중소기업 전용 선복 적재 용량 도 현재보다 주당 50TEU 늘려 공급하겠습니다. 하반기에 우리 기업들의 수출 기회를 늘리기 위해 2 500여 개 수출기업을 대상으로 해외 전시회 참가를 지원하는 등 마케팅 지원도 벌이기로 했습니다. 정부는 또 이달 중으로 반도체를 비롯한 첨단 산업 육성 전략을 마련해 수출 증가세를 뒷받침하고 에너지 소비를 줄이기 위한 효율화 방안을 마련해 무역수지 개선에 나서기로 했습니다. YTN 류환홍입니다.',
 '문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준비 7 8월 2만5000원 추가 시 와인 5종 및 생맥주 무제한 제공 인터컨티넨탈 서울 코엑스 브래서리 쿨 섬머 페스타 . 인터컨티넨탈 서울 코엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 

In [12]:
with open("corpus_kor.txt", "w", encoding="utf-8") as f:
    for line in sentences_kor:
        f.write(line + "\n")

# SentencePiece 모델 학습

## 영어

In [13]:
spm.SentencePieceTrainer.train(
    input="corpus_eng.txt",
    model_prefix="spm_models/spm_eng",
    vocab_size=1000,
    model_type="bpe" # bpe, unigram, char 등 가능
)

## 한국어

In [14]:
spm.SentencePieceTrainer.train(
    input="corpus_kor.txt",
    model_prefix="spm_models/spm_kor",
    vocab_size=1000,
    model_type="bpe" # bpe, unigram, char 등 가능
)

# SentencePiece 모델 로드 & 토큰화

In [15]:
tokenizer_eng = spm.SentencePieceProcessor(model_file="spm_models/spm_eng.model")
tokenizer_kor = spm.SentencePieceProcessor(model_file="spm_models/spm_kor.model")

In [16]:
# 예제 문장
example_eng = "I love natural language processing."
example_kor = "저는 자연어 처리를 공부하고 있습니다."

In [17]:
tokens_eng = tokenizer_eng.encode(example_eng, out_type=str)
tokens_kor = tokenizer_kor.encode(example_kor, out_type=str)

In [18]:
print(f"영어 토큰: {tokens_eng}\n한글 토큰: {tokens_kor}")

영어 토큰: ['▁I', '▁lo', 've', '▁n', 'atur', 'al', '▁l', 'ang', 'u', 'age', '▁pro', 'cess', 'ing', '.']
한글 토큰: ['▁', '저', '는', '▁자', '연', '어', '▁', '처', '리', '를', '▁공', '부', '하고', '▁있', '습', '니다', '.']


# 인덱스 변환 및 임베딩 : PyTorch 예시

In [19]:
import torch
from torch import nn

In [20]:
# 문자를 토큰 인덱스로 변환
ids_eng = torch.LongTensor([tokenizer_eng.encode(example_eng)])
ids_kor = torch.LongTensor([tokenizer_kor.encode(example_kor)])

In [21]:
# 임베딩 설정
emb_dim = 16
embedding_eng = nn.Embedding(tokenizer_eng.get_piece_size(), emb_dim)
embedding_kor = nn.Embedding(tokenizer_kor.get_piece_size(), emb_dim)

In [22]:
embedding_eng, embedding_kor

(Embedding(1000, 16), Embedding(1000, 16))

In [23]:
# 임베딩 벡터 생성
embeds_eng = embedding_eng(ids_eng)
embeds_kor = embedding_eng(ids_kor)

In [24]:
embeds_eng.shape, embeds_kor.shape

(torch.Size([1, 14, 16]), torch.Size([1, 17, 16]))

In [25]:
ids_eng

tensor([[ 56, 229,  75,  71, 821,  25,  68, 407, 940, 351, 127, 631,  16, 948]])

In [26]:
embeds_eng

tensor([[[ 9.8969e-01, -8.6911e-02, -1.6090e+00, -1.0287e+00, -7.6764e-01,
           1.2816e+00, -1.2104e-01, -1.5240e+00, -7.4161e-02,  2.7099e+00,
          -3.5525e-01,  1.1502e+00,  1.8703e-01, -1.3240e-02, -4.0528e-01,
          -7.5421e-01],
         [ 1.1456e+00, -8.9331e-01,  2.0223e+00,  6.7370e-01,  1.4751e+00,
          -1.7729e-01,  6.8422e-02,  7.4252e-01,  3.1813e-02, -1.5382e-02,
           4.6028e-01, -7.7863e-01,  4.5507e-01, -1.2569e+00, -7.5795e-01,
           1.1436e+00],
         [ 1.0509e+00, -8.8221e-01, -1.1901e-01,  8.5794e-01,  1.0376e+00,
          -1.0728e+00, -1.8124e+00,  1.0259e+00,  9.5664e-01,  6.1017e-01,
           6.9986e-03,  1.2031e+00, -1.4354e+00,  3.8801e-01,  1.3230e+00,
           6.4073e-01],
         [-1.5045e+00,  1.0520e+00,  5.5166e-01, -6.3862e-01,  1.2961e+00,
          -1.0324e+00,  1.5134e+00,  3.1017e-01,  8.5245e-01, -3.1213e-02,
          -5.5981e-01, -1.1246e+00,  1.5973e+00,  8.4252e-01, -3.8349e-01,
          -8.8376e-01],
    

In [27]:
ids_kor

tensor([[ 80, 375,  84,  61, 167, 136,  80, 419, 120,  97,  38, 115,  20,  11,
         261,  79,  83]])

In [28]:
embeds_kor

tensor([[[-5.2139e-01, -7.4208e-01, -7.3687e-01, -1.5472e+00, -8.8062e-01,
           2.7277e-01,  5.6077e-01, -1.1435e-01,  1.6672e+00,  1.3191e+00,
          -4.9322e-01,  1.3066e+00, -3.7352e-01,  1.0078e+00, -1.9672e-01,
          -1.1033e+00],
         [ 2.8011e-01, -7.6953e-01, -1.2421e+00, -9.2015e-01,  1.3106e-01,
           1.8964e+00, -7.2929e-01, -1.4309e+00,  6.1365e-01, -2.0706e+00,
           3.4300e-01,  1.7890e+00,  1.3101e+00,  1.9794e-01,  1.4810e+00,
          -1.5212e+00],
         [-1.8010e-01,  4.8100e-01, -8.2146e-01,  3.0711e-01, -2.0671e+00,
          -4.7402e-01,  1.3917e+00, -9.1540e-01, -8.0356e-01,  1.6099e-01,
           3.6067e-01, -1.6096e+00, -1.8058e+00, -8.8814e-01, -5.2407e-01,
          -1.0017e+00],
         [ 1.0338e+00, -7.2409e-01,  8.7540e-01, -4.5507e-01, -6.2000e-01,
          -2.8034e-01, -5.2188e-01, -1.6924e-01,  1.7262e-01,  5.1805e-01,
           1.1395e+00, -3.7110e-01, -1.0080e+00, -1.6731e-01,  2.1339e+00,
           3.7308e-01],
    

# 토큰화 방법 비교

In [29]:
# 1) 코퍼스 파일 만들기
corpus = """I love natural language processing.
I love machine learning.
ChatGPT is amazing.
Natural language models are powerful."""
with open("corpus.txt", "w", encoding="utf-8") as f:
    f.write(corpus)

In [30]:
# 2) unigram & bpe 모델 학습 (vocab_size=30, character_coverage=1.0)
for mtype in ["unigram", "bpe"]:
    spm.SentencePieceTrainer.train(
        input="corpus.txt",
        model_prefix=f"spm_models/spm_{mtype}",
        vocab_size=40,
        model_type=mtype,
        character_coverage=1.0
    )

In [31]:
# 3) 학습된 모델 로드
sp_unigram = spm.SentencePieceProcessor(model_file="spm_models/spm_unigram.model")
sp_bpe     = spm.SentencePieceProcessor(model_file="spm_models/spm_bpe.model")

In [32]:
# 4) 샘플 문장 토큰화
sample = "I love natural language processing."
tokens_unigram = sp_unigram.encode(sample, out_type=str)
tokens_bpe     = sp_bpe.encode(sample,     out_type=str)

In [33]:
# 5) char & word 방식은 수동 분할
tokens_char = [c if c != " " else "▁" for c in sample]
tokens_word = sample.split(" ")

In [34]:
# 6) 결과 출력
print("unigram:", tokens_unigram, "→", len(tokens_unigram), "tokens")
print("bpe    :", tokens_bpe,     "→", len(tokens_bpe),     "tokens")
print("char   :", tokens_char,    "→", len(tokens_char),    "tokens")
print("word   :", tokens_word,    "→", len(tokens_word),    "tokens")

unigram: ['▁', 'I', '▁l', 'o', 'v', 'e', '▁', 'n', 'at', 'u', 'r', 'a', 'l', '▁l', 'a', 'ng', 'u', 'a', 'g', 'e', '▁p', 'r', 'o', 'c', 'e', 's', 's', 'in', 'g', '.'] → 30 tokens
bpe    : ['▁', 'I', '▁l', 'ov', 'e', '▁', 'n', 'at', 'u', 'r', 'al', '▁l', 'a', 'ng', 'u', 'ag', 'e', '▁', 'p', 'r', 'o', 'c', 'e', 's', 's', 'ing', '.'] → 27 tokens
char   : ['I', '▁', 'l', 'o', 'v', 'e', '▁', 'n', 'a', 't', 'u', 'r', 'a', 'l', '▁', 'l', 'a', 'n', 'g', 'u', 'a', 'g', 'e', '▁', 'p', 'r', 'o', 'c', 'e', 's', 's', 'i', 'n', 'g', '.'] → 35 tokens
word   : ['I', 'love', 'natural', 'language', 'processing.'] → 5 tokens
